spring:
  flyway:
    baseline-on-migrate: true
  cache:
    type: redis
    cache-names: runtimes
    redis:
      time-to-live: 60000
      cache-null-values: false
      use-key-prefix: true

  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: validate
    open-in-view: true

  datasource:
    url: jdbc:postgresql://localhost:5432/autograder
    username: root
    password: root
    driverClassName: org.postgresql.Driver
  sql:
    init:
      platform: postgres
client-url: http://localhost:8081/submission-test-result